### ISSUE TITLE
Fehlermld bei aktivem Modul, Shop geht in Wartungsmodus

### ISSUE THREAD

**Issue by swinde** [proudcommerce/psRedirect404#2]
OXID Logger.ERROR: Class 'OxidEsales\EshopCommunity\Internal\Application\ContainerFactory' not found
OXID 6.2.3
Php 7.4
die gesamte Fehlermeldung:
'[2021-02-01 23:01:55] OXID Logger.ERROR: Class 'OxidEsales\EshopCommunity\Internal\Application\ContainerFactory' not found ["[object] (Error(code: 0): Class 'OxidEsales\\EshopCommunity\\Internal\\Application\\ContainerFactory' not found at /srv/www/kaese-shop/public/oxid/source/modules/pc/redirect404/Application/Core/SeoLevenstein.php:130)\n[stacktrace]\n#0 /srv/www/kaese-shop/public/oxid/source/modules/pc/redirect404/Application/Core/SeoLevenstein.php(80): ProudCommerce\\Redirect404\\Application\\Core\\SeoLevenstein->_getSeoUrls()\n#1 /srv/www/kaese-shop/public/oxid/source/modules/pc/redirect404/Application/Core/Utils.php(46): ProudCommerce\\Redirect404\\Application\\Core\\SeoLevenstein->searchUrl()\n#2 /srv/www/kaese-shop/public/oxid/source/overridablefunctions.php(61): ProudCommerce\\Redirect404\\Application\\Core\\Utils->handlePageNotFoundError()\n#3 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/SeoDecoder.php(241): error_404_handler()\n#4 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Config.php(371): OxidEsales\\EshopCommunity\\Core\\SeoDecoder->processSeoCall()\n#5 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Config.php(471): OxidEsales\\EshopCommunity\\Core\\Config->_processSeoCall()\n#6 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Config.php(440): OxidEsales\\EshopCommunity\\Core\\Config->initializeShop()\n#7 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(590): OxidEsales\\EshopCommunity\\Core\\Config->init()\n#8 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(136): OxidEsales\\EshopCommunity\\Core\\ShopControl->_runOnce()\n#9 /srv/www/kaese-shop/public/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Oxid.php(27): OxidEsales\\EshopCommunity\\Core\\ShopControl->start()\n#10 /srv/www/kaese-shop/public/oxid/source/index.php(16): OxidEsales\\EshopCommunity\\Core\\Oxid::run()\n#11 /srv/www/kaese-shop/public/oxid/source/oxseo.php(29): require('/srv/www/kaese-...')\n#12 {main}\n"] []'

**Comment by tabsl** [comment]
feel free to provide an fix ;-)

**Comment by swinde** [comment]
Hallo das habe ich schon versucht aber da enden meine Oxid Programmier Kenntnisse leider!
Edit: Ich glaube ich habe eine Ahnung!
Noch mal Edit! Pull request folgt! ;-)
